version: '3.5'

services:
  influx:
    image: influxdb:1.4.3-alpine
    environment:
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
      INFLUXDB_USER: username
      INFLUXDB_USER_PASSWORD: password
      INFLUXDB_DB: dbname
    ports:
      - 8086:8086

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    depends_on:
      - influx
    volumes:
      - ./grafana:/var/lib/grafana

  mosquitto:
    build: "./docker/mosquitto"
    ports:
      - 1883:1883
    volumes:
      - ./docker/mosquitto/mosquitto.conf:/etc/mosquitto/conf.d/mosquitto.conf
